- name: create maintenance directory
  file:  path={{ home_dir }}/maintenance state=directory owner={{ username }}

- name: create directories for maintenance
  file: path={{ home_dir }}/maintenance/{{ item }} state=directory owner={{ username }}
  with_items:
      - openmrs_war
      - openmrs_modules
      - other_files
      - trusted_sql

- name: Copy tools folder
  copy: src=../../../tools dest={{ home_dir }}/maintenance owner={{ username }}
